name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    # Setup a simple OS of choice, i.e., Linux
    # Create VM with Ubuntu OS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Step 2: List files in the repository
      - name: List repo
        run: |
          ls

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13'

      # Step 4: Install Behave using pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave==1.2.6  # Install Behave with a specific version (adjust version if needed)

      # Step 5: Run Behave tests
      - name: Run Behave tests
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          # Path of the features folder (if not in the root directory)
          test-path: features  # Replace with the actual path to your features folder
          # Name of the output file for results
          test-output-name: results.txt  # Optional, customize as desired
          # Automatically upload the artifact (true/false)
          upload-artifact: true  # Default is true, adjust if needed

